### ISSUE TITLE
Data should be bytearray not string

### ISSUE THREAD

**Issue by karmanyaahm** [UnifiedPush/specifications#20]
Messages should be passed around as byte arrays not strings. Encoding encrypted bytes to UTF-8 results in garbage decoding.

This was recently discussed in #unifiedpush-devs:matrix.org with relation to  https://github.com/binwiederhier/ntfy/issues/101

The spec will probably have to be updated to change data types. This issue exists to keep track of progress regarding that.

**Comment by p1gp1g** [comment]
https://github.com/UnifiedPush/specifications/pull/21

**Comment by karmanyaahm** [comment]
DBus still needs to be done. Since it's 0.x spec, just changing the datatype ought to be fine. I'll open a PR soon
